#    pod 'JVFloatLabeledTextField'
pod 'ParseUI', '~> 1.1'
pod 'Parse'
pod 'MPSkewed'
pod 'GoogleMaps' #, '~> 1.10'
pod 'Masonry'
pod "FBSDKCoreKit" 
pod "FBSDKLoginKit"
pod "AFNetworking", "~> 2.0"
pod "FBSDKShareKit"
pod 'MBProgressHUD', '~> 0.9.1'
pod 'APParallaxHeader'