# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TRVSaveTourTester' do
pod 'FBSDKCoreKit'
pod 'Parse'
pod 'AFNetworking'

end

target 'TRVSaveTourTesterTests' do

end

